export const hotelTypes = [
  "Budget",
  "Boutique",
  "Luxury",
  "Ski",
  "Business",
  "Family",
  "Romantic",
  "Hiking",
  "Cabin",
  "Beach",
  "Golf",
  "All Inclusive",
  "Pet Friendly",
  "Self Catering",
];

export const hotelFacilities = [
  "Free WiFi",
  "Shared kitchen",
  "Shared lounge/TV area",
  "Garden",
  "Board games/Puzzles",
  "Bar",
  "Walking tours",
  "Hiking",
  "Evening entertainment",
  "Bike tours",
  "Movie nights",
  "Soundproof rooms",
  "Game room",
  "Happy hour",
  "Live music/Performance",
  "Bar crawls",
  "Bikes available (free)",
  "Parking",
  "Spa",
  "Fitness Center",
];
